// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tensddhhumfwnmgfyzwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbnNkZGhodW1md25tZ2Z5endoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDA1MzYsImV4cCI6MjA3MzkxNjUzNn0.zs4Zc93q-Yjm39n9bCOZOR4QLcHJZGpIqazZpfuaxuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});